### ISSUE TITLE
Some Android crash reports

### ISSUE THREAD

**Issue by dpogue** [Wizcorp/phonegap-plugin-wizSpinner#28]
We've used this plugin in a project, and didn't have any problems with it, however I was just reviewing crash logs from our testers and there's a few crashes that seem to originate from the plugin.

4.4.2:
```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4222ad60 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:769)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:278)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
	at android.app.Dialog.show(Dialog.java:289)
	at android.app.ProgressDialog.show(ProgressDialog.java:116)
	at android.app.ProgressDialog.show(ProgressDialog.java:104)
	at jp.wizcorp.phonegap.plugin.wizSpinner.WizSpinner$1.run(WizSpinner.java:61)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```

4.2.2
```
java.lang.IllegalArgumentException: View not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:402)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:304)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:83)
	at android.app.Dialog.dismissDialog(Dialog.java:325)
	at android.app.Dialog.dismiss(Dialog.java:307)
	at jp.wizcorp.phonegap.plugin.wizSpinner.WizSpinner$2.run(WizSpinner.java:78)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
```

4.4.2
```
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{42c68e80 V.E..... R.....ID 0,0-1026,288} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:389)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:318)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
	at android.app.Dialog.dismissDialog(Dialog.java:331)
	at android.app.Dialog.dismiss(Dialog.java:314)
	at jp.wizcorp.phonegap.plugin.wizSpinner.WizSpinner$2.run(WizSpinner.java:78)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5293)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aogilvie** [comment]
Thanks! It looks like when your activity is being closed, if the dialog (spinner view) is still open it causes this exception because the dialog is directly attached to the activity.
We'll have to add dialog cleanup code to an onDestroy override method, that should fix these exceptions.

**Comment by CookieMaster** [comment]
Seems like some other event is occurring after the main activity is closed or ended.
Should add a destroy method.
Or possibly onStop
